name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
#     - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
#       shell: bash 
    - run: chmod +x ${{ github.action_path }}/response.txt
      shell: bash
    - name: write to file
      run: curl -s -X GET https://api.agify.io/?name=michael >> ${{ github.action_path }}/response.txt
      shell: bash
    - run: echo "echo 'hi'" >> ${{ github.action_path }}/response.txt
      shell: bash
    - run: ${{ github.action_path }}/bye.sh
      shell: bash
 
    - run: echo 1
      shell: ${{ inputs.who-to-greet }}
    
    - name: Commit and push if changed
      run: |-
        git add .
        git diff
        git config --global user.email "github-action-bot@exampleds.com"
        git config --global user.name "GitHub Action Bot"
        git commit -m "Updated README" -a || echo "No changes to commit"
        git push
      shell: bash
