on:
#   schedule:
#     - cron: "*/5 * * * *" 
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - run: chmod +x ${{ github.action_path }}/README.md
        shell: bash
      - name: write to file
        run: curl -s -X GET https://api.agify.io/?name=michael >> ${{ github.action_path }}/README.md
      - uses: actions/checkout@v3
        with:
          ref: main
      - id: foo
        uses: ./
#         with:
#           who-to-greet: 'Mona the Octocat'
#       - run: echo random-number ${{ steps.foo.outputs.random-number }}
#         shell: bash

